apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nodejs
        pathType: Prefix
        backend:
          service:
            name: nodejs
            port:
              number: 80